feat : #320 create keycloak resource for every files
Ferlab-Ste-Justine/cqdg-etl pull request #12
Opened 2021-06-16 17:02 UTC by creativeyann17

- [ ] Add TUs
- [ ] Move this code to Ferload (tbc)

2021-06-16 18:56 UTC, creativeyann17 commented on src/main/scala/ca/cqdg/etl/utils/KeycloakUtils.scala
> +    val futures = names.map({ name => Future { createResource(name)}})
Just found out that Scala provide parallel collections like stream.parallel of Java. I will maybe change this part with a simplier one.

2021-06-18 12:25 UTC, jecos requested changes

2021-06-18 12:25 UTC, jecos commented on src/main/scala/ca/cqdg/etl/EtlApp.scala
> +        val allFilesInternalIDs = transformedFiles.select("internal_file_id").distinct().collectAsList()
I think you can improve collect here : 
```df.select("column").as[String].collect()```

2021-06-18 12:25 UTC, jecos commented on src/main/scala/ca/cqdg/etl/utils/KeycloakUtils.scala
> +    implicit val executorContext: ExecutionContextExecutorService =
you could define this executorContext as an implicit parameter and inject from the caller. And manage this executerContext outside this function

2021-06-18 12:25 UTC, jecos commented on src/main/scala/ca/cqdg/etl/EtlApp.scala
> +      write(transformedFiles, s"$outputPath/files")
Maybe we should not write if keycloak resource creation did not work

2021-06-18 12:25 UTC, jecos commented on src/main/scala/ca/cqdg/etl/utils/KeycloakUtils.scala
> +    val futures = names.map({ name => Future { createResource(name)}})
Future are OK. But dont use list.map{ a => Future{a}). Future {} shuld be avoid. You can use Future.success instead. But When you have a listyou should you can  also use Future.traverse

2021-06-18 12:25 UTC, jecos commented on src/main/scala/ca/cqdg/etl/utils/KeycloakUtils.scala
> +  def createResources(names: Set[String]): Unit = {
Maybe you should return the Future here, and let the caller to decide what to do in case of Failure

2021-06-21 14:14 UTC, jecos requested changes

2021-06-21 14:14 UTC, jecos commented on src/main/scala/ca/cqdg/etl/utils/KeycloakUtils.scala
> +    existingResource match {
I think you dont need to reutrn an option here, because `Some` is returned in both case. You can do 
``` 
exisingResource.map(_.getId).getOrElse(....)
```

2021-06-21 15:35 UTC, jecos requested changes

2021-06-21 15:35 UTC, jecos commented on src/main/scala/ca/cqdg/etl/EtlApp.scala
> +          case Success(resources) => executorContext.shutdown(); log.info(s"Successfully create ${resources.size} resources")
you should manage shutdown externally. With a shutdown hook :
```
sys.addShutdownHook{...}
```

2021-06-30 14:37 UTC, jecos approved these changes

2021-06-30 14:38 UTC, merged