feat: #330 add data summary
Ferlab-Ste-Justine/cqdg-etl pull request #4
Opened 2021-05-19 18:52 UTC by creativeyann17

**First part of #330**

Example of 

```json
"donors": [...]
"files": [...]
"summary": [
    {
      "data_category": [
        { "key": "Simple nucleotide variation", "donors": 67, "files": 67 },
        { "key": "Sequencing reads", "donors": 199, "files": 199 },
        { "key": "Clinical", "donors": 199, "files": 199 }
      ],
      "experimental_strategy": [{ "key": "WGS", "donors": 199, "files": 266 }],
      "diagnosis": [{ "donors": 199 }],
      "phenotype": [{ "donors": 59 }],
      "treatment": [{ "donors": 199 }]
    }
  ]
```

2021-05-19 19:31 UTC, botekchristophe requested changes

2021-05-19 19:31 UTC, botekchristophe commented on src/main/scala/ca/cqdg/etl/Study.scala
> +      .join(file.as("file"),$"donor.submitter_donor_id" === $"file.submitter_donor_id" && $"donor.study_id" === $"file.study_id")
you can simplify the syntax like this

.join(file, Seq("submitter_donor_id", "study_id")

and remove the two following .drop()

2021-05-19 19:31 UTC, botekchristophe commented on src/main/scala/ca/cqdg/etl/Study.scala
> +  private def computeDonorsAndFilesByField(donor: DataFrame, file: DataFrame, fieldName: String)(implicit spark: SparkSession) : DataFrame = {
extra ' ' before `: DataFrame = {`

2021-05-19 19:31 UTC, botekchristophe commented on src/main/scala/ca/cqdg/etl/Study.scala
> +  private def computeDonorsByField(dataFrame: DataFrame, fieldName: String)(implicit spark: SparkSession) : DataFrame = {
extra ' ' before `: DataFrame = {`

2021-05-19 21:18 UTC, adipaul1981 approved these changes

2021-05-20 12:55 UTC, botekchristophe approved these changes

2021-05-20 13:42 UTC, merged